---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stmarywadihof/app.stmarywadihof
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install --optimize-autoloader --no-dev
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
